version: 1.0.{build}

branches:
  only:
  - 0-3-6

image: Visual Studio 2017

platform: x64

install:
  - ps: Import-Module '.\scripts\appveyor-tool.ps1'
  # - ps: Bootstrap
  - cmd: git submodule update --init --recursive
  # - cmd: .\scripts\msys2.cmd

environment:
  global:
    # VERSION: 0.2.20
    # CC: gcc
    # FC: gfortran
    # BINARY: 64
    # USE_THREAD: 1
    NUM_THREADS: 64
    # NO_SHARED: 1
    # NO_CBLAS: 1
    # NO_LAPACK: 1
    # BUILD_LAPACK_DEPRECATED: 1
    # MAKE_NB_JOBS: 4
    # GEMM_MULTITHREAD_THRESHOLD: 4
    # COMMON_PROF: -pg
    #

  matrix:
    # - TARGET: HASWELL
    - TARGET: SANDYBRIDGE
    # - TARGET: NEHALEM

build:
  parallel: true
  verbosity: minimal

build_script:
  - cd OpenBLAS
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DNUM_THREADS=64 ..
  - cmake --build .
  # - cp ../make/Makefile.rule .
  # - SET PATH=C:\msys64\usr\bin
  # - bash ..\scripts\build.sh

test_script:
  - echo Running Test
  - cd utest
  - openblas_utest

artifacts:
  - path: OpenBLAS/build/lib/**/*

deploy:
  description: 'OpenBLAS compiled for R'
  provider: GitHub
  auth_token:
    secure: 6VduGFAfk0LDLzJDnzCakW7vldMxkkaw4OHCYkFqyecDV9sKE+MdEP5Go4zpmt3c
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
